# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TestCoverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coveralls:

    runs-on: ubuntu-latest

    steps:
    - name: Cloning repo
      uses: actions/checkout@v3
    - name: Use Node.js 15.x
      uses: actions/setup-node@v3
      with:
        node-version: 15.x
        cache: 'npm'
    - name: Installing dependencies    
      run: npm install
    - name: Coverage Test
      run: npm test
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@master
      with: 
        github-token: $({ secrets.GITHUB_TOKEN })
